---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,echo=F,message=F,warning=F}
# Housekeeping

library(survival)
library(survminer)
library(ggplot2)
library(dplyr)
library(DataExplorer)
library(gridExtra)


## Read in Data

dat = read.csv("dukecathr.csv")
dat.unique = dat[dat$RSEQCATHNUM==1,]
attach(dat.unique)

cathdat = data.frame(age = AGE_G, gender = GENDER, race = RACE_G, year = YRCATH_G, 
                     chfsev = CHFSEV, histcereb = HXCEREB, histchf = HXCHF, 
                     histcopd = HXCOPD, histdiab = HXDIAB, histhyp = HXHTN, histmyo = HXMI, 
                     histhyplip = HXHYL, histsmoke = HXSMOKE, height = HEIGHT_R, 
                     weight = WEIGHT_R, s3g = S3, maxsten = LMST, leftvenEF = LVEF_R, numdisves = NUMDZV, death = DEATH, time = DAYS2LKA)
```


```{r,echo=F,message=F,warning=F}


detach(dat.unique)

cols = names(cathdat)[-c(20,21)]
cathdat %<>%
       mutate_each_(funs(factor(.)),cols)

attach(cathdat)


```

```{r,echo=F}
## Create Survival Object

surv_obj = Surv(time = time, event = death)
# surv_obj

```


```{r,echo=F}
## Unstratified Kaplan-Meier Estimate

kp.uns = survfit(surv_obj ~ 1, data = cathdat)
kp.uns.sum = summary(kp.uns)

```

##  Unstratified Kaplan-Meier Estimate

```{r,echo=F}
ggsurvplot(kp.uns, data = cathdat,title="Unstratified Kaplan-Meier Curve")
```

## Stratified Kaplan-Meier Estimates

#### By demographic characteristics
 (Excluding year,age group due to too many categories)

```{r,echo=F}

### Demographics

#### Gender
kp.gender = survfit(surv_obj ~ gender, data = cathdat)
gg.gender = ggsurvplot(kp.gender, data = cathdat,pval = TRUE,title = "By Gender")

#### Race
kp.race = survfit(surv_obj ~ race, data = cathdat,na.action = na.omit)
gg.race = ggsurvplot(kp.race, data = cathdat,pval = TRUE,title = "By Race")

gg.gender
gg.race

```

#### By history of diseases

```{r,echo=F}

#### Cerebrovascular
kp.cereb = survfit(surv_obj ~ histcereb, data = cathdat,na.action = na.omit)
ggcardio =  ggsurvplot(kp.cereb, data = cathdat,pval = TRUE,title = "By Cerebrovascular Disease")

#### Congestive Heart Failure
kp.chf = survfit(surv_obj ~ histchf, data = cathdat,na.action = na.omit)
ggchf = ggsurvplot(kp.chf, data = cathdat,pval = TRUE,title = "By CHF")

#### COPD
kp.copd = survfit(surv_obj ~ histcopd, data = cathdat,na.action = na.omit)
ggcopd = ggsurvplot(kp.copd, data = cathdat,pval = TRUE,title = "By COPD")


#### Diabetes
kp.diab = survfit(surv_obj ~ histdiab, data = cathdat,na.action = na.omit)
ggdiab = ggsurvplot(kp.diab, data = cathdat,pval = TRUE,title = "By Diabetes History")


#### Hypertension
kp.hypt = survfit(surv_obj ~ histhyp, data = cathdat,na.action = na.omit)
gghypt = ggsurvplot(kp.hypt, data = cathdat,pval = TRUE,title = "By Hypertension")


#### Hyperlipidemia
kp.hyplip = survfit(surv_obj ~ histhyplip, data = cathdat,na.action = na.omit)
gghyplip = ggsurvplot(kp.hyplip, data = cathdat,pval = TRUE,title = "By Hyperlipidemia")


#### Myocardial Infarction
kp.myo = survfit(surv_obj ~ histmyo, data = cathdat,na.action = na.omit)
ggmyo = ggsurvplot(kp.myo, data = cathdat,pval = TRUE,title = "By Myocardial Infarction")


#### Smoking
kp.smoke = survfit(surv_obj ~ histsmoke, data = cathdat,na.action = na.omit)
ggsmoke = ggsurvplot(kp.smoke, data = cathdat,pval = TRUE,title = "By Smoking")


ggcardio 
ggchf
ggcopd 
ggdiab
gghypt
gghyplip
ggmyo
ggsmoke

```


#### Other Variables

```{r}

#### S3 Gallop
kp.s3g = survfit(surv_obj ~ s3g, data = cathdat,na.action = na.omit)
ggs3g = ggsurvplot(kp.s3g, data = cathdat,pval = TRUE,title="By S3 Gallop")


#### No. of diseased vessels
kp.disves = survfit(surv_obj ~ numdisves, data = cathdat,na.action = na.omit)
ggdisves = ggsurvplot(kp.disves, data = cathdat,pval = TRUE,title="By No. of Diseased Vessels")

ggs3g
ggdisves

```


