---
title: "Practice 1"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

# Housekeeping
library(survival)
library(survminer)
library(dplyr)

# Data
data(ovarian)

```

# Dataset EDA

```{r}

# Overall

glimpse(ovarian)
help(ovarian)


# Age
 hist(ovarian$age)
 
 
# Dichotomize age and change data labels
 
ovarian$rx <- factor(ovarian$rx, 
                     levels = c("1", "2"), 
                     labels = c("A", "B"))
ovarian$resid.ds <- factor(ovarian$resid.ds, 
                           levels = c("1", "2"), 
                           labels = c("no", "yes"))
ovarian$ecog.ps <- factor(ovarian$ecog.ps, 
                          levels = c("1", "2"), 
                          labels = c("good", "bad"))

ovarian <- ovarian %>% mutate(age_group = ifelse(age >=50, "old", "young"))
ovarian$age_group <- factor(ovarian$age_group)



```

`fustat`- 0 is censored and 1 is not censored

# Non-parametric Kaplan Meier estimate

```{r}

# Create survival object

surv_object <- Surv(time = ovarian$futime, event = ovarian$fustat)
surv_object 

# KP stratified by treatment

fit1 = survfit(surv_object ~ rx, data = ovarian)
summary(fit1)

# Visualize

ggsurvplot(fit1, data = ovarian, pval = TRUE)

```

# COx PH Model

```{r}

# Fit a Cox proportional hazards model

fit.coxph <- coxph(surv_object ~ rx + resid.ds + age_group + ecog.ps, 
                   data = ovarian)
ggforest(fit.coxph, data = ovarian)

```

